<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UserEdit.aspx.cs" Inherits="Doubt_Solving_Website.UserEdit" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">SD</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="home.aspx">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="UserEdit.aspx">Edit Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="logIn.aspx">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="logIn.aspx" >Log out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <form id="form1" runat="server">
        <div>
        <div>
            <center><h2>&nbsp;</h2></center>
        </div>
        <p>
            <asp:Label ID="Label1" runat="server" Text="Username :    "></asp:Label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="uname" runat="server"></asp:TextBox>
            <asp:RequiredFieldValidator ID="uvalidator" runat="server" ControlToValidate="uname" ErrorMessage="Field is Required" ForeColor="Red"></asp:RequiredFieldValidator>
            </p>
        <p>
            <asp:Label ID="Label3" runat="server" Text="Email : " ></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="uemail" runat="server" AutoPostBack="true" OnTextChanged="email_validation_"></asp:TextBox>
            &nbsp;<asp:RequiredFieldValidator ID="evalidator" runat="server" ControlToValidate="uemail" ErrorMessage="Field is Required" ForeColor="Red"></asp:RequiredFieldValidator>
            <br />
            <br />
            <asp:Label ID="Label2" runat="server" Text="Password : "></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="upassword" runat="server" type="password"></asp:TextBox>
            <asp:RequiredFieldValidator ID="pvalidator" runat="server" ControlToValidate="upassword" ErrorMessage="Field is Required" ForeColor="Red"></asp:RequiredFieldValidator>
            <br />
            <br />
            <asp:Button ID="btnUpdate" runat="server" OnClick="btnUpdate_click" Text="Update" />
        </p>
            <p>
                &nbsp;</p>
            <h2>
                Your Doubts :</h2>
            <p>
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
                    <Columns>
                        <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                        <asp:BoundField DataField="Question" HeaderText="Question" SortExpression="Question" />
                        <asp:BoundField DataField="user_id" HeaderText="user_id" SortExpression="user_id" />
                        <asp:BoundField DataField="type" HeaderText="type" SortExpression="type" />
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [Doubts] WHERE ([user_id] = @user_id)" DeleteCommand="Delete from [Doubts] where ([Id]=@Id)">
                    <SelectParameters>
                        <asp:SessionParameter Name="user_id" SessionField="user_id" Type="Int32" />
                    </SelectParameters>
                </asp:SqlDataSource>
            </p>
        </div>
    </form>
</body>
</html>
